In [1]:
import seaborn as sns
df=sns.load_dataset('titanic')
import numpy as np
import pandas as pd

In [2]:
DF = df.to_csv('titanic.csv', index = False)
df.sample(4)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
531         0       3    male   NaN      0      0   7.2292        C   Third   
314         0       2    male  43.0      1      1  26.2500        S  Second   
342         0       2    male  28.0      0      0  13.0000        S  Second   
156         1       3  female  16.0      0      0   7.7333        Q   Third   

       who  adult_male deck  embark_town alive  alone  
531    man        True  NaN    Cherbourg    no   True  
314    man        True  NaN  Southampton    no  False  
342    man        True  NaN  Southampton    no   True  
156  woman       False  NaN   Queenstown   yes   True

In [3]:
##['sex','embarked','alone','pclass','Survived']
df=df[['sex','embarked','alone','pclass','survived']]
df.head()

sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

In [4]:
df['sex']=np.where(df['sex']=="male",1,0) #put 1 where sex is male and 
#0 where sex is female
df.head()

sex embarked  alone  pclass  survived
0    1        S  False       3         0
1    0        C  False       1         1
2    0        S   True       3         1
3    0        S  False       1         1
4    1        S   True       3         0

In [6]:
# Let's perform label encoding on sex column
import numpy as np
# let's perform label encoding on embarked
ordinal_label = {k: i for i, k in enumerate(df['embarked'].unique(), 0)}
df['embarked'] = df['embarked'].map(ordinal_label)

In [8]:
# let's perform label encoding on alone
df['alone']=np.where(df['alone']==True,1,0)
df.head()

sex  embarked  alone  pclass  survived
0    1         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    1         0      1       3         0

In [13]:
#train Test split is usually done to avaoid overfitting
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['sex','embarked','alone','pclass']],
                                               df['survived'],test_size=0.3,random_state=100)
X_train.head()

sex  embarked  alone  pclass
69     1         0      0       3
85     0         0      0       3
794    1         0      1       3
161    0         0      1       2
815    1         0      1       1

In [14]:
X_train['sex'].unique()


array([1, 0])

In [15]:
X_train.isnull().sum()

sex         0
embarked    0
alone       0
pclass      0
dtype: int64

In [16]:
## Perform chi2 test
### chi2 returns 2 values
### Fscore and the pvalue
from sklearn.feature_selection import chi2
f_p_values=chi2(X_train,y_train)

In [17]:
f_p_values

(array([65.67929505,  7.55053653, 10.88471585, 21.97994154]),
 array([5.30603805e-16, 5.99922095e-03, 9.69610546e-04, 2.75514881e-06]))

In [18]:
import pandas as pd
p_values=pd.Series(f_p_values[1])
p_values.index=X_train.columns
p_values

sex         5.306038e-16
embarked    5.999221e-03
alone       9.696105e-04
pclass      2.755149e-06
dtype: float64

In [19]:
p_values.sort_index(ascending=False)

sex         5.306038e-16
pclass      2.755149e-06
embarked    5.999221e-03
alone       9.696105e-04
dtype: float64

Conclusion: sex column is most important  column when compared to the output feature Survived